nixpacks.version = "1.x"

[phases.setup]
nixPkgs = ["...", "jdk17"]

[phases.build]
cmds = ["./mvnw clean package -DskipTests"]

[start]
cmd = "java -Dserver.port=$PORT -jar target/demo-0.0.1-SNAPSHOT.jar"
