services:
  # Spring Boot Web Application
  - type: web
    name: nextgenkart-app
    runtime: docker
    plan: free
    region: oregon
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: OPENAI_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DATABASE
        value: ecommerce
      - key: SPRING_PROFILES_ACTIVE
        value: prod
